shu immediate;
startup mount;
alter database archivelog;
alter database open;
ALTER DATABASE FORCE LOGGING;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER SYSTEM SWITCH LOGFILE;

SELECT supplemental_log_data_min, force_logging FROM v$database;
select name,log_mode from v$database;

CREATE USER GGADMIN IDENTIFIED BY "GG##lab12345" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CREATE SESSION TO GGADMIN;
GRANT CONNECT TO GGADMIN;
GRANT RESOURCE TO GGADMIN;
GRANT ALTER ANY TABLE TO GGADMIN;
GRANT ALTER SYSTEM TO GGADMIN;
GRANT CREATE TABLE TO GGADMIN;
GRANT DBA TO GGADMIN;
GRANT SELECT ANY DICTIONARY TO GGADMIN;
GRANT SELECT ANY TRANSACTION TO GGADMIN;

EXEC DBMS_GOLDENGATE_AUTH.GRANT_ADMIN_PRIVILEGE('GGADMIN','*',TRUE,TRUE);

alter system set enable_goldengate_replication = true scope=both;

alter user HR identified by "GG##lab12345" account unlock;

exit;